const twos_data = {
  AA: {
    def: "rough, cindery lava [n AAS]",
    front_hooks: "b",
    back_hooks: "hls",
    canonical: "AA",
  },
  AB: {
    def: "an abdominal muscle [n ABS]",
    front_hooks: "cdfgjklnstw",
    back_hooks: "asy",
    canonical: "AB",
  },
  AD: {
    def: "an advertisement [n ADS]",
    front_hooks: "bcdfghlmprstw",
    back_hooks: "dosz",
    canonical: "AD",
  },
  AE: {
    def: "one [adj]",
    front_hooks: "ghkmnstw",
    back_hooks: "",
    canonical: "AE",
  },
  AG: {
    def: "agriculture [n AGS]",
    front_hooks: "bdfghjlmnrstwyz",
    back_hooks: "aeos",
    canonical: "AG",
  },
  AH: {
    def: "aah (to exclaim in amazement, joy, or surprise) [v AHED, AHING, AHS]",
    front_hooks: "abdfhlnpry",
    back_hooks: "ais",
    canonical: "AH",
  },
  AI: {
    def: "a three-toed sloth [n AIS]",
    front_hooks: "r",
    back_hooks: "dlmnrst",
    canonical: "AI",
  },
  AL: {
    def: "an East Indian tree [n ALS]",
    front_hooks: "abcdgps",
    back_hooks: "abelpst",
    canonical: "AL",
  },
  AM: {
    def: "BE, to have actuality [v]",
    front_hooks: "bcdghjlmnprty",
    back_hooks: "aipu",
    canonical: "AM",
  },
  AN: {
    def: "used before words beginning with a vowel sound [article]",
    front_hooks: "bcdfgmnprstvw",
    back_hooks: "adeity",
    canonical: "AN",
  },
  AR: {
    def: "the letter R [n ARS]",
    front_hooks: "bcefgjlmoptvwy",
    back_hooks: "bcefkmst",
    canonical: "AR",
  },
  AS: {
    def: "to the same degree [adv]",
    front_hooks: "abdfghklmprtvwyz",
    back_hooks: "hkps",
    canonical: "AS",
  },
  AT: {
    def: "in the position of [prep]",
    front_hooks: "bcefghklmopqrstvw",
    back_hooks: "et",
    canonical: "AT",
  },
  AW: {
    def: "used to express protest, disgust, or disbelief [interj]",
    front_hooks: "cdhjlmnprstvwy",
    back_hooks: "aeln",
    canonical: "AW",
  },
  AX: {
    def: "to work on with an ax (a type of cutting tool) [v AXED, AXES, AXING]",
    front_hooks: "flmprstwz",
    back_hooks: "e",
    canonical: "AX",
  },
  AY: {
    def: "aye (an affirmative vote) [n AYS]",
    front_hooks: "bcdfghjklmnprswy",
    back_hooks: "es",
    canonical: "AY",
  },
  BA: {
    def: "the eternal soul, in Egyptian mythology [n BAS]",
    front_hooks: "ao",
    back_hooks: "adghlmnprsty",
    canonical: "BA",
  },
  BE: {
    def: "to have actuality [v AM, ARE, ART, BEEN, BEING, IS, WAS, WAST, WERE, WERT]",
    front_hooks: "o",
    back_hooks: "deglnsty",
    canonical: "BE",
  },
  BI: {
    def: "a bisexual (one who is attracted to both sexes) [n BIS]",
    front_hooks: "o",
    back_hooks: "bdgnostz",
    canonical: "BI",
  },
  BO: {
    def: "a pal [n BOS]",
    front_hooks: "",
    back_hooks: "abdgopstwxy",
    canonical: "BO",
  },
  BY: {
    def: "a pass in certain card games [n BYS]",
    front_hooks: "a",
    back_hooks: "es",
    canonical: "BY",
  },
  DA: {
    def: "dad (father) [n DAS]",
    front_hooks: "o",
    back_hooks: "bdghklmnpswy",
    canonical: "DA",
  },
  DE: {
    def: "of; from -- used in names [prep]",
    front_hooks: "o",
    back_hooks: "beflnpvwxy",
    canonical: "DE",
  },
  DO: {
    def: "the first tone of the diatonic musical scale [n DOS] / to begin and carry through to completion [v DID, DIDST, DOES, DOEST, DOETH, DOING, DONE, DOST, DOTH]",
    front_hooks: "au",
    back_hooks: "ceghlmnrstw",
    canonical: "DO",
  },
  ED: {
    def: "education [n EDS]",
    front_hooks: "bfglmprtwxz",
    back_hooks: "hs",
    canonical: "ED",
  },
  EF: {
    def: "the letter F [n EFS]",
    front_hooks: "dkr",
    back_hooks: "fst",
    canonical: "EF",
  },
  EH: {
    def: "used to express doubt or surprise [interj]",
    front_hooks: "fhmpy",
    back_hooks: "",
    canonical: "EH",
  },
  EL: {
    def: "an elevated railroad or train [n ELS]",
    front_hooks: "bcdegmst",
    back_hooks: "dfklms",
    canonical: "EL",
  },
  EM: {
    def: "the letter M [n EMS]",
    front_hooks: "fghmr",
    back_hooks: "eosu",
    canonical: "EM",
  },
  EN: {
    def: "the letter N [n ENS]",
    front_hooks: "bdfghkmpstwyz",
    back_hooks: "dgs",
    canonical: "EN",
  },
  ER: {
    def: "used to express hesitation [interj]",
    front_hooks: "fhpsy",
    back_hooks: "aegnrs",
    canonical: "ER",
  },
  ES: {
    def: "ess (the letter S) [n ESES]",
    front_hooks: "bfhmoprty",
    back_hooks: "st",
    canonical: "ES",
  },
  ET: {
    def: "EAT, to consume food [v]",
    front_hooks: "bfghjlmnprstvwy",
    back_hooks: "ah",
    canonical: "ET",
  },
  EW: {
    def: "expressing disgust [interj] (2018)",
    front_hooks: "defhmnpsty",
    back_hooks: "e",
    canonical: "EW",
  },
  EX: {
    def: "to cross out [v EXED, EXES, EXING]",
    front_hooks: "dhklrsv",
    back_hooks: "",
    canonical: "EX",
  },
  FA: {
    def: "the fourth tone of the diatonic musical scale [n FAS]",
    front_hooks: "",
    back_hooks: "bdghnrstxy",
    canonical: "FA",
  },
  FE: {
    def: "a Hebrew letter [n FES]",
    front_hooks: "",
    back_hooks: "dehmnrstuwyz",
    canonical: "FE",
  },
  GI: {
    def: "a white garment worn in martial arts [n GIS]",
    front_hooks: "",
    back_hooks: "bdefgnpst",
    canonical: "GI",
  },
  GO: {
    def: "a Japanese board game [n GOS] / to move along [v GOES, GOING, GONE, GWINE, WENT]",
    front_hooks: "ae",
    back_hooks: "abdorstx",
    canonical: "GO",
  },
  HA: {
    def: "a sound of surprise [n HAS]",
    front_hooks: "asw",
    back_hooks: "deghjmopstwy",
    canonical: "HA",
  },
  HE: {
    def: "a male person [n HES]",
    front_hooks: "st",
    back_hooks: "hmnprstwxy",
    canonical: "HE",
  },
  HI: {
    def: "used as a greeting [interj]",
    front_hooks: "acgkp",
    back_hooks: "cdemnpst",
    canonical: "HI",
  },
  HM: {
    def: "hmm (used to express thoughtful consideration) [interj]",
    front_hooks: "o",
    back_hooks: "m",
    canonical: "HM",
  },
  HO: {
    def: "used to express surprise [interj]",
    front_hooks: "moprstw",
    back_hooks: "bdegmnoptwy",
    canonical: "HO",
  },
  ID: {
    def: "a part of the psyche [n IDS]",
    front_hooks: "abdfghklmrv",
    back_hooks: "s",
    canonical: "ID",
  },
  IF: {
    def: "a possibility [n IFS]",
    front_hooks: "dgkr",
    back_hooks: "fs",
    canonical: "IF",
  },
  IN: {
    def: "to harvest (to gather a crop) [v INNED, INNING, INS]",
    front_hooks: "abdfghjklprstvwyz",
    back_hooks: "kns",
    canonical: "IN",
  },
  IS: {
    def: "BE, to have actuality [v]",
    front_hooks: "abcdghklmpqstvwx",
    back_hooks: "m",
    canonical: "IS",
  },
  IT: {
    def: "the 3d person sing. neuter pronoun [pron]",
    front_hooks: "abdfghklnpstwz",
    back_hooks: "s",
    canonical: "IT",
  },
  JO: {
    def: "a sweetheart [n JOES]",
    front_hooks: "",
    back_hooks: "begtwy",
    canonical: "JO",
  },
  KA: {
    def: "the spiritual self of a human being in Egyptian religion [n KAS]",
    front_hooks: "os",
    back_hooks: "befsty",
    canonical: "KA",
  },
  KI: {
    def: "qi (the vital force that in Chinese thought is inherent in all things) [n KIS]",
    front_hooks: "s",
    back_hooks: "dfnprst",
    canonical: "KI",
  },
  LA: {
    def: "the sixth tone of the diatonic musical scale [n LAS]",
    front_hooks: "a",
    back_hooks: "bcdghmprstvwxy",
    canonical: "LA",
  },
  LI: {
    def: "a Chinese unit of distance [n LIS]",
    front_hooks: "",
    back_hooks: "bdenpst",
    canonical: "LI",
  },
  LO: {
    def: "used to attract attention or to express surprise [interj]",
    front_hooks: "",
    back_hooks: "bgoprtwx",
    canonical: "LO",
  },
  MA: {
    def: "mother [n MAS]",
    front_hooks: "ao",
    back_hooks: "cdegmnprstwxy",
    canonical: "MA",
  },
  ME: {
    def: "an ego (the conscious self) [n MES]",
    front_hooks: "e",
    back_hooks: "dghlmnstw",
    canonical: "ME",
  },
  MI: {
    def: "the third tone of the diatonic musical scale [n MIS]",
    front_hooks: "a",
    back_hooks: "bcdglmrsx",
    canonical: "MI",
  },
  MM: {
    def: "used to express assent or satisfaction [interj]",
    front_hooks: "hmu",
    back_hooks: "m",
    canonical: "MM",
  },
  MO: {
    def: "a moment (a brief period of time) [n MOS]",
    front_hooks: "e",
    back_hooks: "abcdgilmnoprstw",
    canonical: "MO",
  },
  MU: {
    def: "a Greek letter [n MUS]",
    front_hooks: "ae",
    back_hooks: "dgmnstx",
    canonical: "MU",
  },
  MY: {
    def: "the possessive form of the pronoun I [pron]",
    front_hooks: "",
    back_hooks: "c",
    canonical: "MY",
  },
  NA: {
    def: "no; not [adv]",
    front_hooks: "a",
    back_hooks: "beghmnpvwy",
    canonical: "NA",
  },
  NE: {
    def: "born with the name of [adj]",
    front_hooks: "ao",
    back_hooks: "begtw",
    canonical: "NE",
  },
  NO: {
    def: "a negative reply [n NOES, NOS]",
    front_hooks: "o",
    back_hooks: "bdghmorstw",
    canonical: "NO",
  },
  NU: {
    def: "a Greek letter [n NUS]",
    front_hooks: "g",
    back_hooks: "bgnst",
    canonical: "NU",
  },
  OD: {
    def: "a hypothetical force of natural power [n ODS]",
    front_hooks: "bcghmnprsty",
    back_hooks: "ades",
    canonical: "OD",
  },
  OE: {
    def: "a whirlwind off the Faeroe islands [n OES]",
    front_hooks: "dfhjrtvw",
    back_hooks: "s",
    canonical: "OE",
  },
  OF: {
    def: "coming from [prep]",
    front_hooks: "o",
    back_hooks: "ft",
    canonical: "OF",
  },
  OH: {
    def: "to exclaim in surprise, pain, or desire [v OHED, OHING, OHS]",
    front_hooks: "dfnops",
    back_hooks: "mos",
    canonical: "OH",
  },
  OI: {
    def: "oy (used to express dismay or pain) [interj]",
    front_hooks: "kmp",
    back_hooks: "kl",
    canonical: "OI",
  },
  OK: {
    def: "okay [adj] (2018)",
    front_hooks: "wy",
    back_hooks: "ae",
    canonical: "OK",
  },
  OM: {
    def: "a mantra used in contemplation of ultimate reality [n OMS]",
    front_hooks: "dhmnprsty",
    back_hooks: "as",
    canonical: "OM",
  },
  ON: {
    def: "the side of the wicket where a batsman stands in cricket [n ONS]",
    front_hooks: "cdefhimstwy",
    back_hooks: "eos",
    canonical: "ON",
  },
  OP: {
    def: "a style of abstract art [n OPS]",
    front_hooks: "bcfhklmpst",
    back_hooks: "aest",
    canonical: "OP",
  },
  OR: {
    def: "the heraldic color gold [n ORS]",
    front_hooks: "cdfgklmnt",
    back_hooks: "abcegst",
    canonical: "OR",
  },
  OS: {
    def: "a bone [n OSSA] / an esker (a narrow ridge of gravel and sand) [n OSAR] / an orifice (a mouth or mouthlike opening) [n ORA]",
    front_hooks: "bcdgkmnpsw",
    back_hooks: "e",
    canonical: "OS",
  },
  OW: {
    def: "used to express sudden pain [interj]",
    front_hooks: "bcdhjlmnprstvwy",
    back_hooks: "elnt",
    canonical: "OW",
  },
  OX: {
    def: "a clumsy person [n OXES] / a hoofed mammal [n OXEN]",
    front_hooks: "bcfglpsv",
    back_hooks: "oy",
    canonical: "OX",
  },
  OY: {
    def: "used to express dismay or pain [interj]",
    front_hooks: "bcfhjst",
    back_hooks: "",
    canonical: "OY",
  },
  PA: {
    def: "a father [n PAS]",
    front_hooks: "os",
    back_hooks: "cdhklmnprstwxy",
    canonical: "PA",
  },
  PE: {
    def: "a Hebrew letter [n PES]",
    front_hooks: "ao",
    back_hooks: "acdeghnprstw",
    canonical: "PE",
  },
  PI: {
    def: "a Greek letter [n PIS] / to jumble or disorder [v PIED, PIEING, PIES, PIING]",
    front_hooks: "",
    back_hooks: "acegnpstux",
    canonical: "PI",
  },
  PO: {
    def: "a chamber pot [n POS]",
    front_hooks: "au",
    back_hooks: "dhilmopstwx",
    canonical: "PO",
  },
  QI: {
    def: "the vital force that in Chinese thought is inherent in all things [n QIS]",
    front_hooks: "",
    back_hooks: "s",
    canonical: "QI",
  },
  RE: {
    def: "the second tone of the diatonic musical scale [n RES]",
    front_hooks: "aeio",
    back_hooks: "bcdefgimpstvxz",
    canonical: "RE",
  },
  SH: {
    def: "used to urge silence [interj]",
    front_hooks: "a",
    back_hooks: "aehoy",
    canonical: "SH",
  },
  SI: {
    def: "ti (the seventh tone of the diatonic musical scale) [n SIS]",
    front_hooks: "p",
    back_hooks: "bcgmnprstx",
    canonical: "SI",
  },
  SO: {
    def: "sol (the fifth tone of the diatonic musical scale) [n SOS]",
    front_hooks: "",
    back_hooks: "bcdhlmnpstuwxy",
    canonical: "SO",
  },
  TA: {
    def: "an expression of gratitude [n TAS]",
    front_hooks: "eu",
    back_hooks: "bdegjmnoprstuvwx",
    canonical: "TA",
  },
  TE: {
    def: "ti (the seventh tone of the diatonic musical scale) [n TES]",
    front_hooks: "au",
    back_hooks: "acdeglnstw",
    canonical: "TE",
  },
  TI: {
    def: "the seventh tone of the diatonic musical scale [n TIS]",
    front_hooks: "",
    back_hooks: "celnpstxz",
    canonical: "TI",
  },
  TO: {
    def: "in the direction of [prep]",
    front_hooks: "",
    back_hooks: "degmnoprtwy",
    canonical: "TO",
  },
  UH: {
    def: "used to express hesitation [interj]",
    front_hooks: "dh",
    back_hooks: "",
    canonical: "UH",
  },
  UM: {
    def: "to hesitate or pause in speaking [v UMMED, UMMING, UMS]",
    front_hooks: "bcdghlmrstvy",
    back_hooks: "mps",
    canonical: "UM",
  },
  UN: {
    def: "one [pron UNS]",
    front_hooks: "bdfghjlmnprst",
    back_hooks: "is",
    canonical: "UN",
  },
  UP: {
    def: "to raise (to move to a higher position) [v UPPED, UPPING, UPS]",
    front_hooks: "cdhpsty",
    back_hooks: "os",
    canonical: "UP",
  },
  US: {
    def: "the objective case of the pronoun we [pron]",
    front_hooks: "bjmnps",
    back_hooks: "e",
    canonical: "US",
  },
  UT: {
    def: "the musical tone C in the French solmization system now replaced by do [n UTS]",
    front_hooks: "bcghjmnoprt",
    back_hooks: "aes",
    canonical: "UT",
  },
  WE: {
    def: "1st person pl. pronoun in the nominative case [pron]",
    front_hooks: "aeo",
    back_hooks: "bdent",
    canonical: "WE",
  },
  WO: {
    def: "woe (tremendous grief) [n WOS]",
    front_hooks: "t",
    back_hooks: "eknostw",
    canonical: "WO",
  },
  XI: {
    def: "a Greek letter [n XIS]",
    front_hooks: "",
    back_hooks: "s",
    canonical: "XI",
  },
  XU: {
    def: "a monetary unit of Vietnam [n XU]",
    front_hooks: "",
    back_hooks: "",
    canonical: "XU",
  },
  YA: {
    def: "an Asian pear [n YAS]",
    front_hooks: "pr",
    back_hooks: "ghkmprswy",
    canonical: "YA",
  },
  YE: {
    def: "you [pron]",
    front_hooks: "abdeklprtw",
    back_hooks: "ahnprstwz",
    canonical: "YE",
  },
  YO: {
    def: "used to call attention or to express affirmation [interj]",
    front_hooks: "",
    back_hooks: "bdkmnuw",
    canonical: "YO",
  },
  ZA: {
    def: "a pizza (an Italian open pie) [n ZAS]",
    front_hooks: "",
    back_hooks: "gpsx",
    canonical: "ZA",
  },
};
